#!/usr/bin/env bash

usage_and_exit () {
    echo "Usage: video2binary <infile> <outfile>"
    exit $1
}

if [ $# = 1 -a x$1 = 'x--help' ]; then
   usage_and_exit 0
fi

if [ $# != 2 ]; then
    usage_and_exit 1
fi

tmpfile_gzipped=$(mktemp --tmpdir video2binary.gz.XXXXXXXXXX)

infile="$1"
outfile="$2"
gzip=/usr/bin/gzip
ffmpeg=/usr/bin/ffmpeg
pixel_format=rgb24

$ffmpeg -y -hide_banner -loglevel error \
    -i "${infile}" -f rawvideo -pix_fmt rgb24 "${tmpfile_gzipped}"
size_gzipped=$(stat --format=%s ${tmpfile_gzipped})
echo "gzipped file has $size_gzipped bytes"

$gzip -d -c "${tmpfile_gzipped}" > ${outfile}
echo "output file has $(stat --format=%s ${outfile}) bytes"
md5sum ${outfile}

rm ${tmpfile_gzipped}
